### ISSUE TITLE
Commissioning of a node failing  in B-series inconsistently

### ISSUE THREAD

**Issue by pradvara** [contiv/cluster#172] opened 2016-08-19 08:44 UTC
- Commission node in B-series

[stack@contiv-b1 ~]$ ansible --version
ansible 2.1.1.0
  config file = /home/stack/ansible.cfg
  configured module search path = Default w/o overrides

[stack@contiv-b1 ansible]$ clusterctl job get last | grep -e FAILED -e RECAP
    fatal: [contiv-b1-FCH1702J22M]: FAILED! => {"changed": true, "cmd": "netctl global set --fwd-mode \"bridge\"", "delta": "0:00:01.609496", "en                                                    :06:36.059252", "failed": true, "rc": 2, "start": "2016-08-17 11:06:34.449756", "stderr": "panic: runtime error: invalid memory address or nil po                                                    n[signal 0xb code=0x1 addr=0x38 pc=0x47eb60]\n\ngoroutine 1 [running]:\npanic(0x7e5100, 0xc82000e120)\n\t/usr/local/go/src/runtime/panic.go:481 +                                                    contiv/netplugin/netctl.setGlobal(0xc8200a9440)\n\t/opt/gopath/src/github.com/contiv/netplugin/netctl/netctl.go:637 +0x150\ngithub.com/contiv/net                                                    ub.com/codegangsta/cli.Command.Run(0x8668b8, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0x8aa0d0, 0x15, 0x0, ...)\n\t/opt/gopath/src/github.com/contiv/netplug                                                    om/codegangsta/cli/command.go:131 +0x1058\ngithub.com/contiv/netplugin/vendor/github.com/codegangsta/cli.(*App).RunAsSubcommand(0xc8200a9200, 0xc                                                    0)\n\t/opt/gopath/src/github.com/contiv/netplugin/vendor/github.com/codegangsta/cli/app.go:280 +0x1163\ngithub.com/contiv/netplugin/vendor/github                                                    li.Command.startApp(0x8654c8, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x8a9070, 0x12, 0x0, ...)\n\t/opt/gopath/src/github.com/contiv/netplugin/vendor/githu                                                    cli/command.go:209 +0x7c1\ngithub.com/contiv/netplugin/vendor/github.com/codegangsta/cli.Command.Run(0x8654c8, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x8a                                                    ..)\n\t/opt/gopath/src/github.com/contiv/netplugin/vendor/github.com/codegangsta/cli/command.go:59 +0x15f6\ngithub.com/contiv/netplugin/vendor/gi                                                    ta/cli.(*App).Run(0xc8200a8fc0, 0xc82000a050, 0x5, 0x5, 0x0, 0x0)\n\t/opt/gopath/src/github.com/contiv/netplugin/vendor/github.com/codegangsta/cl                                                    2\nmain.main()\n\t/opt/gopath/src/github.com/contiv/netplugin/netctl/netctl/main.go:16 +0x12c", "stdout": "", "stdout_lines": [], "warnings": []}
    PLAY RECAP *********************************************************************

**Comment by vvb** [comment] 2016-08-19 13:18
@pradvara thanks for reporting this issue. I tried and have successfully reproduced this issue. This looks like a netplugin issue.

**Comment by mapuri** [comment] 2016-08-19 15:53
@pradvara yes @vvb is correct. If netmaster is not ready then netctl commands fails.

This is fixed in recent ansible (as part of https://github.com/contiv/ansible/pull/262) to wait on netmaster to be ready. So updating the ansible should resolve this error. We can close this once you have verified.

Not sure if the panic itself is being tracked in netplugin.  /cc @abhinandanpb

**Comment by abhinandanpb** [comment] 2016-08-19 15:55
@mapuri I have added checks in one of my larger set of changes. Yet to commi them.

**Comment by mapuri** [comment] 2016-08-19 15:56
awesome, thanks @abhinandanpb !

**Comment by vvb** [comment] 2016-08-19 16:12
awesome, thanks @mapuri 

@abhinandanpb can you link the PR/issue that you are going to commit your change to. That way we will know when can be close this issue.

**Comment by pradvara** [comment] 2016-08-19 16:58
Thank you @mapuri , @abhinandanpb @vvb , thank you, will check with the latest commit

**Comment by pradvara** [comment] 2016-08-22 08:38
@mapuri I tried updating the ansible,  I see the netplugin is not starting this time.


[stack@contiv-b1 ansible]$ ansible --version
ansible 2.1.1.0
  config file = /home/stack/ansible/ansible.cfg
  configured module search path = Default w/o overrides



[stack@contiv-b1 ansible]$ ansible --version
ansible 2.1.1.0
  config file = /home/stack/ansible/ansible.cfg
  configured module search path = Default w/o overrides
[stack@contiv-b1 ansible]$ sudo systemctl status netplugin
● netplugin.service - Netplugin
   Loaded: loaded (/etc/systemd/system/netplugin.service; static; vendor preset: disabled)
   Active: inactive (dead)

Aug 22 11:39:21 contiv-b1 netplugin[20459]: time="Aug 22 11:39:21.916187458" level=info msg="AddMaster for {HostAddr:10.106.240.108 Port:9001}"
Aug 22 11:39:21 contiv-b1 netplugin[20459]: time="Aug 22 11:39:21.916211710" level=info msg="Adding master: {HostAddr:10.106.240.108 HostPort:9001}"
Aug 22 11:39:21 contiv-b1 netplugin[20459]: time="Aug 22 11:39:21.916717895" level=info msg="Adding master: {HostAddr:10.106.240.108 HostPort:9001}"
Aug 22 11:39:33 contiv-b1 netplugin[20459]: time="Aug 22 11:39:33.196653767" level=info msg="Handling \"activate\" event"
Aug 22 11:39:33 contiv-b1 netplugin[20459]: time="Aug 22 11:39:33.197375835" level=info msg="Handling \"getCapability\" event"
Aug 22 11:39:33 contiv-b1 netplugin[20459]: time="Aug 22 11:39:33.197939058" level=info msg="Handling \"getIpamCapability\" event"
Aug 22 11:39:33 contiv-b1 netplugin[20459]: time="Aug 22 11:39:33.198371997" level=info msg="Handling \"getDefaultAddressSpaces\" event"
Aug 22 11:39:33 contiv-b1 netplugin[20459]: time="Aug 22 11:39:33.198395847" level=info msg="Body content: "
Aug 22 11:40:46 contiv-b1 systemd[1]: Stopping Netplugin...
Aug 22 11:40:46 contiv-b1 systemd[1]: Stopped Netplugin.




[stack@contiv-b1 ansible]$ clusterctl job get last | grep -e FAILED -e RECAP
    FAILED - RETRYING: TASK: contiv_network : wait for netmaster to be ready (9 retries left).
    FAILED - RETRYING: TASK: contiv_network : wait for netmaster to be ready (8 retries left).
    FAILED - RETRYING: TASK: contiv_network : wait for netmaster to be ready (7 retries left).
    FAILED - RETRYING: TASK: contiv_network : wait for netmaster to be ready (6 retries left).
    FAILED - RETRYING: TASK: contiv_network : wait for netmaster to be ready (5 retries left).
    FAILED - RETRYING: TASK: contiv_network : wait for netmaster to be ready (4 retries left).
    FAILED - RETRYING: TASK: contiv_network : wait for netmaster to be ready (3 retries left).
    FAILED - RETRYING: TASK: contiv_network : wait for netmaster to be ready (2 retries left).
    FAILED - RETRYING: TASK: contiv_network : wait for netmaster to be ready (1 retries left).
    fatal: [contiv-b1-FCH1702J22M]: FAILED! => {"changed": true, "cmd": "netctl tenant ls", "delta": "0:00:00.015617", "end": "2016-08-22 11:40:43.730445", "failed": true, "rc": 3, "start": "2016-08-22 11:40:43.714828", "stderr": "time=\"2016-08-22T11:40:43+05:30\" level=error msg=\"503 Service Unavailable\" ", "stdout": "", "stdout_lines": [], "warnings": []}
    PLAY RECAP *********************************************************************
    fatal: [contiv-b1-FCH1702J22M]: FAILED! => {"changed": false, "failed": true, "msg": "systemd could not find the requested service \"'aci-gw'\": "}
    fatal: [contiv-b1-FCH1702J22M]: FAILED! => {"changed": false, "failed": true, "msg": "systemd could not find the requested service \"'kubernetes'\": "}
    PLAY RECAP *********************************************************************

**Comment by mapuri** [comment] 2016-08-22 15:59
@pradvara did you set `no_proxy` in the `env` variables? Setting it in globals or per command should be fine.

The new ansible is definitely taking effect as it seems from the `wait for netmaster to be ready` logs. But we will need `no_proxy` (whenever http_proxy is set) to be set for  netctl be able to reach netmaster. This is usually the case for setups that run behind proxy (which I believe is true for your setup as well).

Kindly correct me if I missed something.

**Comment by pradvara** [comment] 2016-08-23 05:19
@mapuri , i tried with "no_proxy"

[stack@contiv-b1 ansible]$ clusterctl global get
extra_vars:
    env:
        http_proxy: http://proxy-wsa.esl.cisco.com:80
        https_proxy: http://proxy-wsa.esl.cisco.com:80
        no_proxy: 127.0.0.1,localhost,netmaster

I am facing the same error, please correct me if anything needs to be added here

[stack@contiv-b1 ansible]$ clusterctl job get last | grep -e FAILED -e RECAP
    FAILED - RETRYING: TASK: contiv_network : wait for netmaster to be ready (9 retries left).
    FAILED - RETRYING: TASK: contiv_network : wait for netmaster to be ready (8 retries left).
    FAILED - RETRYING: TASK: contiv_network : wait for netmaster to be ready (7 retries left).
    FAILED - RETRYING: TASK: contiv_network : wait for netmaster to be ready (6 retries left).
    FAILED - RETRYING: TASK: contiv_network : wait for netmaster to be ready (5 retries left).
    FAILED - RETRYING: TASK: contiv_network : wait for netmaster to be ready (4 retries left).
    FAILED - RETRYING: TASK: contiv_network : wait for netmaster to be ready (3 retries left).
    FAILED - RETRYING: TASK: contiv_network : wait for netmaster to be ready (2 retries left).
    FAILED - RETRYING: TASK: contiv_network : wait for netmaster to be ready (1 retries left).
    fatal: [contiv-b1-FCH1702J22M]: FAILED! => {"changed": true, "cmd": "netctl tenant ls", "delta": "0:00:00.012974", "end": "2016-08-23 09:10:34.040140", "failed": true, "rc": 3, "start": "2016-08-23 09:10:34.027166", "stderr": "time=\"2016-08-23T09:10:34+05:30\" level=error msg=\"503 Service Unavailable\" ", "stdout": "", "stdout_lines": [], "warnings": []}
    PLAY RECAP *********************************************************************

**Comment by mapuri** [comment] 2016-08-23 16:51
@pradvara hmm, can't think of any other obvious reasons. 

Just to make sure that env is set correctly, can you dump the json using `clusterctl global get --json`

Also feel free to slack me the setup details, I can take a look as well.

**Comment by pradvara** [comment] 2016-08-23 17:08
[stack@contiv-b1 ~]$ clusterctl global get --json
{
    "extra_vars": {
        "env": {
            "http_proxy": "http://proxy-wsa.esl.cisco.com:80",
            "https_proxy": "http://proxy-wsa.esl.cisco.com:80",
            "no_proxy": "127.0.0.1,localhost,netmaster"
        }
    }

**Comment by mapuri** [comment] 2016-08-23 19:27
@pradvara 

Closing this based on discussion on slack.

Just to summarize the findings and close the loop basically the `env` was correctly set in globals but it was getting overridden by `env` specified in the commission command (which was missing the `no_proxy` setting). Removing the `env` from commission command fixed the problem.

**Closed by mapuri** 2016-08-23 19:27 UTC
